from typing import Any, Protocol, TypeVar

from common.types import WorkerMessage

ReceiptHandleT = TypeVar("ReceiptHandleT")


class QueueService(Protocol[ReceiptHandleT]):
    name: str

    def __init__(self, queue_name: str, deadletter_queue_name: str, **kwargs: Any) -> None: ...

    def receive_message(self, max_messages: int = 10) -> list[tuple[WorkerMessage, ReceiptHandleT]]: ...

    def publish_message(self, message: WorkerMessage) -> None: ...

    def complete_message(self, receipt_handle: ReceiptHandleT) -> None: ...

    def deadletter_message(self, message: WorkerMessage, receipt_handle: ReceiptHandleT) -> None: ...

    def abandon_message(self, receipt_handle: ReceiptHandleT) -> None: ...

    def purge_messages(self) -> None: ...
